language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jagoncalves/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jagoncalves/docker-react npm run test